esphome:
  name: navipals-box
  friendly_name: NaviPals Box
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    - light.turn_on:
        id: led
        blue: 100%
        brightness:  !lambda |-
                      return 1*(id(led_brightness).state * 0.01);
        effect: fast pulse

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
   
psram:
  mode: octal # Please change this to quad for N8R2 and octal for N16R8
  speed: 80MHz

logger:

api:
  encryption:
    key: !secret navipal_key

ota:
  - platform: esphome
    password: !secret navipal_ota_pw

wifi:
  networks:
  - ssid: !secret wifi_ssid_office
    password: !secret wifi_password_office
    priority: 2
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  ap:
    ssid: "NaviPal"
    password: !secret navipal_ap_pw

captive_portal:

improv_serial:

number:
  - platform: template
    name: "LED brightness"
    optimistic: true
    min_value: 10
    max_value: 100
    step: 1
    id: led_brightness
    restore_value: True

text_sensor:
  - platform: template
    name: Recived Text
    id: stt
  - platform: template
    name: Responce Text
    id: tts
  - platform: template
    name: Brite
    id: brit
        
i2s_audio:
  - id: i2s_in # For microphone
    i2s_lrclk_pin: GPIO3  #WS 
    i2s_bclk_pin: GPIO2 #SCK

  - id: i2s_speaker #For Speaker
    i2s_lrclk_pin: GPIO6  #LRC 
    i2s_bclk_pin: GPIO7 #BLCK

microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: GPIO4 #SD
    channel: left
    adc_type: external
    i2s_audio_id: i2s_in
    pdm: false
    bits_per_sample: 32bit

voice_assistant:
  microphone: echo_microphone
  media_player: media_out
  conversation_timeout: 20s
  on_start:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        brightness:  !lambda |-
                      return 1*(id(led_brightness).state * 0.01);
        effect: none
  on_listening: 
    - light.turn_on:
        id: led
        blue: 0%
        red: 0%
        green: 50%
        brightness:  !lambda |-
                      return 1*(id(led_brightness).state * 0.01);
        effect: Rainbow Effect With Custom Values
  on_intent_start:
    then:
      - media_player.toggle:
          id: media_out
  on_stt_end: 
    - text_sensor.template.publish:
        id: stt
        state: !lambda 'return x;'
  on_tts_start:
    - text_sensor.template.publish:
        id: tts
        state: !lambda 'return x;'
    - light.turn_on:
        id: led
        blue: 75%
        red: 0%
        green: 100%
        brightness:  !lambda |-
                      return 1*(id(led_brightness).state * 0.01);
        effect: pulse
  on_tts_end:
    - media_player.play_media: !lambda return x;
    - light.turn_on:
        id: led
        blue: 100%
        red: 50%
        green: 0%
        brightness:  !lambda |-
                      return 1*(id(led_brightness).state * 0.01);
        effect: talking
  on_end:
    - delay: 1s
    - wait_until:
        not:
          media_player.is_playing: media_out
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        brightness:  !lambda |-
                      return 1*(id(led_brightness).state * 0.01);
        effect: none
  on_error:
    - light.turn_on:
        id: led
        blue: 0%
        red: 100%
        green: 0%
        brightness:  !lambda |-
                      return 1*(id(led_brightness).state * 0.01);
        effect: none
    - delay: 1s
    - light.turn_off: led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10  #Physical Button connected to this pin.
      inverted: True
      mode:
        input: True
        pullup: True
    name: Button
    id: echo_button
    on_press:
      if:
        any:
          - media_player.is_playing:
          - media_player.is_announcing
        then:
          - media_player.stop
        else:
          - media_player.toggle:
              id: media_out
          - delay: 5ms
          - voice_assistant.start:

button:
  - platform: template
    name: Mic On
    id: my_button
    icon: "mdi:emoticon-outline"
    on_press:
      - logger.log: "Button pressed"
      - media_player.toggle:
          id: media_out
      - delay: 5ms
      - voice_assistant.start:
speaker:
  - platform: i2s_audio
    id: output_speaker
    i2s_dout_pin: GPIO8   #  DIN Pin of the MAX98357A Audio
    dac_type: external
    i2s_audio_id: i2s_speaker
    bits_per_sample: 32bit
    channel: right
    buffer_duration: 60ms

media_player:
  - platform: speaker
    id: media_out
    name: Media Player
    announcement_pipeline:
      speaker: output_speaker
      format: WAV
    codec_support_enabled: false
    buffer_size: 6000
    on_play:
      - logger.log: "Playback started."
    on_announcement:
       - logger.log: "Playback started (Announcement)."
       - light.turn_on:
          id: led
          blue: 75%
          red: 100%
          green: 0%
          brightness:  !lambda |-
                      return 1*(id(led_brightness).state * 0.01);
          effect: talking
    on_pause:
         - logger.log: "Playback paused."
    on_idle:
         - logger.log: "Playback stopped."
         - light.turn_on:
            id: led
            blue: 100%
            red: 0%
            green: 0%
            brightness:  !lambda |-
                      return 1*(id(led_brightness).state * 0.01);
            effect: none

light:
  - platform: esp32_rmt_led_strip
    id: led
    name: LED Ring
    pin: GPIO09
    default_transition_length: 0s
    chipset: ws2812
    num_leds: 16
    rgb_order: grb
    on_turn_on:
      - light.turn_on:
          id: led
    effects:
      - pulse:
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
      - pulse:
          name: "Talking"
          transition_length: 0.2s
          update_interval: 0.2s
          min_brightness: 0%
          max_brightness: 25%
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 40
          width: 50
