esphome:
  name: navipals-box
  friendly_name: NaviPals Box

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret navipal_key

ota:
  - platform: esphome
    password: !secret navipal_ota_pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "NaviPal"
    password: !secret navipal_ap_pw

captive_portal:

improv_serial:


globals:
  - id: global_brightness
    type: float
    restore_value: true
    initial_value: '0.5'  # 50% brightness

number:
  - platform: template
    name: "LED Brightness"
    id: brightness_control
    min_value: 0
    max_value: 1
    step: 0.05
    optimistic: true
    initial_value: 0.5
    restore_value: True
    set_action:
      - globals.set:
          id: global_brightness
          value: !lambda 'return x;'
      - light.control:
          id: led
          brightness: !lambda 'return id(global_brightness);'

text_sensor:
  - platform: template
    name: Recived Text
    id: stt
  - platform: template
    name: Responce Text
    id: tts
  - platform: template
    name: Brite
    id: brit

 # Audio and Voice Assistant Config          
i2s_audio:
  - id: i2s_in # For microphone
    i2s_lrclk_pin: GPIO18  #WS 
    i2s_bclk_pin: GPIO8 #GPIO2 #SCK

  - id: i2s_speaker #For Speaker
    i2s_lrclk_pin: GPIO6  #LRC 
    i2s_bclk_pin: GPIO7 #BLCK

sensor:
  - platform: adc
    pin: GPIO05
    name: "Battery"
    update_interval: 60s

microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: GPIO17 #SD
    channel: left
    adc_type: external
    i2s_audio_id: i2s_in
    pdm: false
    bits_per_sample: 32bit

voice_assistant:
  microphone: echo_microphone
  media_player: media_out
  noise_suppression_level: 1
  auto_gain: 10dBFS
  volume_multiplier: 2.0
  on_listening: 
    - light.turn_on:
        id: led
        blue: 0%
        red: 0%
        green: 50%
        brightness: !lambda 'return id(global_brightness);'
        effect: Rainbow Effect With Custom Values
  on_stt_end: 
    - text_sensor.template.publish:
        id: stt
        state: !lambda 'return x;'
  on_tts_start:
    - text_sensor.template.publish:
        id: tts
        state: !lambda 'return x;'
  on_tts_end:
    - media_player.play_media: !lambda return x;
  on_error:
    - light.turn_on:
        id: led
        blue: 0%
        red: 100%
        green: 0%
        brightness: !lambda 'return id(global_brightness);'
        effect: none
    - delay: 1s
    - light.turn_off: led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10  #Physical Button connected to this pin.
      inverted: True
      mode:
        input: True
        pullup: True
    name: Button
    id: echo_button
    on_press:
      if:
        any:
          - media_player.is_playing:
          - media_player.is_announcing
        then:
          - media_player.stop
        else:
          - media_player.stop:
              id: media_out
          - delay: 5ms
          - voice_assistant.start:

# Example button configuration
button:
  - platform: template
    name: Mic On
    id: my_button
    # Optional variables:
    icon: "mdi:emoticon-outline"
    on_press:
      - logger.log: "Button pressed"
      - media_player.stop:
          id: media_out
      - delay: 5ms
      - voice_assistant.start:

speaker:
  - platform: i2s_audio
    i2s_audio_id: i2s_speaker
    id: s3_speaker
    i2s_dout_pin: GPIO15 #  DIN Pin of the MAX98357A Audio
    dac_type: external
    bits_per_sample: 32bit
    channel: right
    buffer_duration: 60ms

media_player:
  - platform: speaker
    id: media_out
    name: Media Player
    announcement_pipeline:
      speaker: s3_speaker
      format: WAV
    codec_support_enabled: false
    buffer_size: 6000
    volume_min: 0.4
    on_announcement:
       - light.turn_on:
          id: led
          blue: 75%
          red: 100%
          green: 0%
          brightness: !lambda 'return id(global_brightness);'
          effect: talking
    on_idle:
         - light.turn_on:
            id: led
            blue: 100%
            red: 0%
            green: 0%
            brightness: !lambda 'return id(global_brightness);'
            effect: none

light:
  - platform: esp32_rmt_led_strip
    id: led
    name: LED Ring
    pin: GPIO16
    default_transition_length: 0s
    chipset: ws2812
    num_leds: 16
    rgb_order: grb
    on_turn_on:
      - light.turn_on:
          id: led
    effects:
      - pulse:
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          #max_brightness: 20%
      - pulse:
          name: "Talking"
          transition_length: 0.2s
          update_interval: 0.2s
          min_brightness: 0%
          max_brightness: 25%
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 40
          width: 50
